### ISSUE TITLE
RAG API server is not being triggered

### ISSUE THREAD

**Issue by gjyotin305** [GaiaNet-AI/gaianet-node#123]
Here I made a snapshot using the gaianet web tool, about WASMEdge Organisation.

My Logs are given below:

- Qdrant Logs 
[start-qdrant.log](https://github.com/user-attachments/files/16462316/start-qdrant.log)

- Llama Edge logs
[start-llamaedge.log](https://github.com/user-attachments/files/16462317/start-llamaedge.log)

An attachement of what is happening is 
![image](https://github.com/user-attachments/assets/b91f7c6c-cfae-4e79-b8a8-1937c1ef8e3f)

Only the RAG api server is not working for some weird reason.

**Comment by juntao** [comment]
Can you share your `config.json` file?

**Comment by gjyotin305** [comment]
@juntao 

[config.json](https://github.com/user-attachments/files/16466508/config.json)

**Comment by juntao** [comment]
It seems that the `system-prompt` and `rag-prompt` are swapped. The `rag-prompt` should tell the model to use the context.

**Comment by gjyotin305** [comment]
> It seems that the `system-prompt` and `rag-prompt` are swapped. The `rag-prompt` should tell the model to use the context.
> 
> 

I think even then it should atleast show the logs for rag api server.

Let me try swapping them as well.

**Comment by gjyotin305** [comment]
@juntao 

New Config  [config.json](https://github.com/user-attachments/files/16468768/config.json)

Qdrant dashboard is also not visible 

Responses with New Config:

![image](https://github.com/user-attachments/assets/a8c297f5-7249-4688-ad74-18aca99e44ff)

**Comment by gjyotin305** [comment]
Qdrant logs

- [start-qdrant.log](https://github.com/user-attachments/files/16468789/start-qdrant.log)
- [init-qdrant.log](https://github.com/user-attachments/files/16468791/init-qdrant.log)

**Comment by apepkuss** [comment]
@gjyotin305 Could you please run the following three commands and tell us the results? Thanks.

```bash
# version of gaianet CLI tool
gaianet --version

# wasmedge version
wasmedge --version

# rag-api-server version
wasmedge rag-api-server.wasm -V
```

**Comment by apepkuss** [comment]
@gjyotin305 I noticed that you're using `wasmedge 0.14.0`. Please switch to `wasmedge 0.13.5` as all versions of `gaianet-node` only works with `0.13.5`. In addition, please use the following official command to install gaianet-node, and the command will also deploy the correct version of WasmEdge + plugins. After that, please retry your queries. Thanks!

```bash
curl -sSfL 'https://github.com/GaiaNet-AI/gaianet-node/releases/latest/download/install.sh' | bash
```

**Comment by apepkuss** [comment]
The [release page](https://github.com/GaiaNet-AI/gaianet-node/releases/tag/0.2.5) of `GaiaNet-Node v0.2.5` lists the versions of all components.

**Comment by gjyotin305** [comment]
Got it to work @apepkuss wasmedge version was the problem thanks.
