### ISSUE TITLE
一直显示 proxy异常，我换了三个梯子

### ISSUE THREAD

**Issue by kobe-tian** [GaiaNet-AI/gaianet-node#54]
** 一直显示 proxy异常，我换了三个梯子**
![image](https://github.com/GaiaNet-AI/gaianet-node/assets/54635927/929383c4-66c1-4809-9c25-a93beacd4c88)

**Comment by longzhi** [comment]
Your network access seems to have encountered an issue. Please check.

**Comment by apepkuss** [comment]
@kobe-tian 梯子通常不会在terminal中缺省生效，需要额外的操作。你可以在开启梯子的情况，先用浏览器访问huggingface.co，确保梯子有效；然后，再根据你所用的梯子app，具体看如何在termianl中也生效。

**Comment by RecursionHs** [comment]
这个你就别找项目方了，只可能是你梯子问题。用tun模式
