### ISSUE TITLE
ERROR: Gainet node not starting

### ISSUE THREAD

**Issue by Rumeyst** [GaiaNet-AI/gaianet-node#60]
* Start a Qdrant instance ...

    * Remove the existed 'default' Qdrant collection ...

    * Download Qdrant collection snapshot ...
############################################################################ 100.0%      The snapshot is downloaded in /root/gaianet

    * Import the Qdrant collection snapshot ...
      The process may take a few minutes. Please wait ...
      Recovery is done!

[+] Preparing the dashboard ...
You already have a private key.

[+] Preparing the GaiaNet domain ...

[+] COMPLETED! GaiaNet node is initialized successfully.

>>> To start the GaiaNet node, run the command: gaianet start <<<

root@vmi1735894:~# gaianet start
[+] Checking the config.json file ...

[+] Starting Qdrant instance ...

    Qdrant instance started with pid: 6147

[+] Starting LlamaEdge API Server ...

    Port 8080 is in use. Exit ...

    Stopping Qdrant instance ...
/root/gaianet/bin/gaianet: line 550:  6147 Killed                  nohup $qdrant_executable > $log_dir/start-qdrant.log 2>&1  (wd: ~/gaianet/qdrant)
root@vmi1735894:~#  --port <val>

**Comment by alabulei1** [comment]
Hi @Rumeyst 

Could you please try the following things? From your log, I can see that a node is running on your machine now.

First, please stop the running node.

```
gaianet stop
```

Second, use `gaianet start` to start running your node.

```
gaianet start
```

Let me know if it works for you. Thanks.

**Comment by Rumeyst** [comment]
alright will do that now

**Comment by alabulei1** [comment]
Hi @Rumeyst 

Juts want to make sure that you have run the Gaianet Node successsfully.

**Comment by Rumeyst** [comment]
Yes! it started successfully after rebooting the system.
