### ISSUE TITLE
/root/gaianet/bin/gaianet: line 549: 467161 Illegal instruction in Debian

### ISSUE THREAD

**Issue by phanuwit267** [GaiaNet-AI/gaianet-node#61]
gaianet start and pid: 467161 not working

<img width="1140" alt="Screenshot 2567-06-02 at 15 45 23" src="https://github.com/GaiaNet-AI/gaianet-node/assets/24976372/53aa9637-43ef-4ed4-ae2d-e0d937d730ad">

**Comment by apepkuss** [comment]
According to the messages in the snapshot, it seems that Qdrant instance did not start correctly. If a Qdrant instance starts correctly, the pid will be printed on the screen.

**Comment by phanuwit267** [comment]
I have successfully switched to ubuntu.

thank you.
