### ISSUE TITLE
Completely remove Gaianet Node from Linux server?

### ISSUE THREAD

**Issue by theVasilis** [GaiaNet-AI/gaianet-node#75]
Dear team, I'm looking to completely remove Gaianet Node and all its added packages from my Debian VPS.

I would like to do a clean install without any remnant of the old installation.

Is there a guide or a set of commands to do that?

Thank you very much.

**Comment by zmunro** [comment]
There is an `uninstall.sh` file at the base of the repository which should be what you are looking for :)

**Comment by theVasilis** [comment]
> There is an `uninstall.sh` file at the base of the repository which should be what you are looking for :)

Thank you very much @zmunro 

Is that going to also remove Chat Agents and Region files? 

Or do I have to do that manually?

**Comment by alabulei1** [comment]
Hi @zmunro  and @theVasilis 

Thanks for your help. @zmunro  You're right. 

Please use the following command line to clean your environment.

```
curl -sSfL 'https://github.com/GaiaNet-AI/gaianet-node/releases/latest/download/uninstall.sh' | bash
```

**Comment by theVasilis** [comment]
Thank you very much @alabulei1
