### ISSUE TITLE
Not able to run custom snapshot.tar.gz

### ISSUE THREAD

**Issue by codemaster1104** [GaiaNet-AI/gaianet-node#76]
I was experimenting some things with gaianet custom nodes and wanted to just test how embedding works and work with custom data for same I created a snapshot following [documentation](https://docs.gaianet.ai/creator-guide/knowledge/text/) for same Paris dataset and have added [snapshot.tar.gz](https://huggingface.co/Ak1104/snapshot/blob/main/my.snapshot.tar.gz) to my github and have updated the config file accordingly

`  "address": "0x8ed74092f0d0e0752a7fa5d7b9a2a81a6646a53e",
  "chat": "https://huggingface.co/gaianet/Llama-3-8B-Instruct-GGUF/resolve/main/Meta-Llama-3-8B-Instruct-Q5_K_M.gguf",
  "chat_ctx_size": "4096",
  "chat_name": "LLAMA-3-8B-Instruct-GGUF",
  "description": "The default GaiaNet node config with a Phi-3-mini-4k model and a Paris tour guide knowledge base.",
  "domain": "us.gaianet.network",
  "embedding": "nomic-embed-text-v1.5.f16.gguf",
  "embedding_collection_name": "default",
  "embedding_ctx_size": "512",
  "embedding_name": "Nomic-embed-text-v1.5",
  "llamaedge_port": "8080",
  "prompt_template": "llama-3-chat",
  "qdrant_limit": "1",
  "qdrant_score_threshold": "0.5",
  "rag_policy": "system-message",
  "rag_prompt": "You are a tour guide in London, UK. Use information in the following context to directly answer the question from a London visitor.\n----------------\n",
  "reverse_prompt": "",
  "snapshot": "https://huggingface.co/Ak1104/snapshot/blob/main/my.snapshot.tar.gz",
  "system_prompt": "You are a tour guide in London, UK. Please answer the question from a London visitor accurately."
}`

# Note
I already had embedding model locally so in this code I have added its relative path instead of huggingface link

Now when I perform git init I am running into 
`gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
`
and if I try to add my relative path of snapshot to "snapshot" tag i run into
`curl: (6) Could not resolve host: my.snapshot.tar.gz                           
Warning: Transient problem: timeout Will retry in 1 seconds. 3 retries left.
curl: (6) Could not resolve host: my.snapshot.tar.gz                           
Warning: Transient problem: timeout Will retry in 2 seconds. 2 retries left.
curl: (6) Could not resolve host: my.snapshot.tar.gz                           
Warning: Transient problem: timeout Will retry in 4 seconds. 1 retries left.
curl: (6) Could not resolve host: my.snapshot.tar.gz  `

I am successfully able to run [Llama3_London tour guide](https://docs.gaianet.ai/node-guide/customize) example from documentation, not sure whats going wrong for my self created snapshot

**Comment by alabulei1** [comment]
Hi @codemaster1104 

From the config.json file you provided, I found that the snapshot link is wrong. You should use `https://huggingface.co/Ak1104/snapshot/resolve/main/my.snapshot.tar.gz`, which is the correct download link.

**Comment by codemaster1104** [comment]
Thanks @alabulei1 got it working with that link

**Comment by alabulei1** [comment]
Great! I will close this PR. Let us know if you have any other questions.
